# Generated by Django 5.2.7 on 2025-10-16 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rut', models.CharField(db_index=True, max_length=20)),
                ('student_name', models.CharField(max_length=120)),
                ('course_name', models.CharField(max_length=60)),
                ('period', models.CharField(max_length=20)),
                ('amount_clp', models.PositiveIntegerField()),
                ('method', models.CharField(max_length=30)),
                ('evidence_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], db_index=True, default='PENDING', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_approve', 'Puede aprobar pagos')],
            },
        ),
    ]
