# Generated by Django 5.2.6 on 2025-10-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='id',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='name',
        ),
        migrations.AddField(
            model_name='grade',
            name='curso_id',
            field=models.CharField(default='PG', max_length=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='curso_nombre',
            field=models.CharField(default='Curso Temporal', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
