# Generated by Django 5.2.7 on 2025-10-24 21:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='issue_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de emisión del pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateField(blank=True, help_text='Fecha en que se completó el pago', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('overdue', 'Vencido'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(help_text='Título o asunto del comunicado', max_length=200)),
                ('mensaje', models.TextField(help_text='Contenido del mensaje a enviar')),
                ('destino', models.CharField(choices=[('todos', 'Todos los usuarios'), ('curso', 'Por curso'), ('manual', 'Correo manual')], help_text='Destino del comunicado (todos, curso o manual)', max_length=20)),
                ('destinatarios', models.TextField(blank=True, help_text='Correos separados por coma a los que se envió este comunicado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
