# Generated by Django 5.2.7 on 2025-11-21 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_subjectschedule_sched_end_after_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guardian_payment_pin',
            field=models.CharField(blank=True, help_text='PIN de autorización de pagos del apoderado', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('pending_review', 'En revisión'), ('rejected', 'Rechazado'), ('overdue', 'Vencido'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='UploadedPaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.FileField(upload_to='comprobantes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('comentario_finanzas', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, help_text='Cuota asociada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_proofs', to='core.payment')),
                ('revisado_por', models.ForeignKey(blank=True, limit_choices_to={'role': 'finance_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_revisados', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
