# Generated by Django 5.2.6 on 2025-10-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_role_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
