# Generated by Django 5.2.7 on 2025-10-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subjectschedule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subjectschedule',
            name='sched_end_after_start',
        ),
        migrations.AddConstraint(
            model_name='subjectschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='sched_end_after_start'),
        ),
    ]
