# Generated by Django 5.2.6 on 2025-10-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Alumno'), ('guardian', 'Apoderado'), ('teacher', 'Profesor'), ('admin', 'Administrador'), ('finance_admin', 'Administrador de Finanzas')], default='student', max_length=20),
        ),
    ]
