# Generated by Django 5.2.6 on 2025-10-24 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subjectschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('destino', models.CharField(choices=[('todos', 'Todos los usuarios'), ('curso', 'Por curso'), ('manual', 'Correo manual')], max_length=20)),
                ('destinatarios', models.TextField(blank=True, help_text='Correos separados por coma')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
